"""Check the corpus labels against what real models actually do.

Every number Little Leo reports rests on an assumption nobody has tested: that a
turn labelled ``SMALL`` can genuinely be handled by a small model. The labels
were generated by rule. If the rule is wrong, the router faithfully reproduces a
wrong definition of difficulty and the measured "savings" are quality loss
wearing a discount.

This script tests that assumption, and it is the only part of the project that
spends money.

Method
------

For each held-out turn: ask a cheap model and a frontier model the same
question, then show both answers to a *third-vendor* judge with the order
randomised and the sources hidden, and ask whether the cheaper answer is
materially worse.

The judge is neither contestant. An OpenAI model scoring OpenAI against DeepSeek
would be marking its own family's homework, and the result would be unusable
however it came out.

What this can and cannot establish
----------------------------------

It replaces "my generator asserted this is SMALL" with "a frontier model, shown
both answers blind, judged the small one adequate". That is better evidence. It
is not proof: the judge is itself a model with its own preferences, it sees a
single response rather than a conversation, and it is being asked a question
with genuinely debatable answers. The model card should say so.

Spending
--------

Cost is computed from the usage each response actually reports, not estimated.
A ceiling is checked before every call and the run aborts the moment the next
call could breach it. Partial results are written continuously, so an abort
costs nothing already paid for.

    python scripts/ground_labels.py --per-category 50 --ceiling 4.50
"""

from __future__ import annotations

import argparse
import json
import random
import sys
import time
import urllib.error
import urllib.request
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from littleleo.grounding_fixture import ITEMS, TIER_NAMES  # noqa: E402
from littleleo.providers import openrouter_key, openrouter_pricing  # noqa: E402

CHEAP = "deepseek/deepseek-v4-flash"
FRONTIER = "openai/gpt-5.4"          # gpt-5.3 exists only as a codex variant
JUDGE = "anthropic/claude-opus-4.5"  # third vendor: neutral to both contestants

ENDPOINT = "https://openrouter.ai/api/v1/chat/completions"

#: Answers are capped. The judge needs enough to assess quality, and an
#: uncapped frontier model on a vague prompt can produce two thousand tokens of
#: preamble at fifteen dollars a million.
#: Per-model token budgets, because a single cap is wrong when one model
#: reasons internally and the other does not.
#:
#: Measured, not guessed: deepseek-v4-flash spent 701 reasoning tokens on a
#: 700-token budget and returned ZERO visible characters, while gpt-5.4 answered
#: the same prompt in 468 tokens with no reasoning at all. A shared cap silently
#: deleted the cheap model's hardest answers -- and since those were the items it
#: found hardest, dropping them made it look better than it is.
ANSWER_TOKENS = {
    "deepseek/deepseek-v4-flash": 2500,   # reasoning budget plus an answer
    "openai/gpt-5.4": 1200,
}
DEFAULT_ANSWER_TOKENS = 1200
MAX_JUDGE_TOKENS = 250

ANSWER_SYSTEM = (
    "You are an assistant embedded in a developer's tooling. Answer the user's "
    "turn directly and completely. Do not ask clarifying questions; if the turn "
    "is ambiguous, state your assumption in one line and proceed."
)

JUDGE_SYSTEM = (
    "You are evaluating two answers to the same request, labelled A and B. "
    "Decide whether one is MATERIALLY worse than the other for the person who "
    "asked.\n\n"
    "'Materially worse' means it would change what they do next: it is wrong, "
    "it misses the point, it ignores a stated constraint, or it fails to "
    "deliver what was asked for. Stylistic differences, length, tone and "
    "formatting are NOT material. If both answers would serve the person "
    "equally well, say EQUIVALENT.\n\n"
    "Reply with exactly one line of JSON and nothing else:\n"
    '{\"verdict\": \"A_WORSE\" | \"B_WORSE\" | \"EQUIVALENT\", '
    '\"reason\": \"<fifteen words or fewer>\"}'
)


class Budget:
    """Tracks real spend and refuses the call that would breach the ceiling."""

    def __init__(self, ceiling_usd: float, pricing: dict):
        self.ceiling = ceiling_usd
        self.pricing = pricing
        self.spent = 0.0
        self.calls = 0

    def cost_of(self, model: str, prompt_tokens: int, completion_tokens: int) -> float:
        rates = self.pricing.get(model)
        if not rates:
            return 0.0
        return (prompt_tokens * rates["prompt_per_mtok_usd"] / 1e6
                + completion_tokens * rates["completion_per_mtok_usd"] / 1e6)

    def would_breach(self, model: str, headroom_multiplier: float = 1.0) -> bool:
        """Worst case for one more call: full prompt plus a full answer."""
        cap = ANSWER_TOKENS.get(model, DEFAULT_ANSWER_TOKENS)
        worst = self.cost_of(model, 2000, cap) * headroom_multiplier
        return (self.spent + worst) > self.ceiling

    def record(self, model: str, usage: dict) -> float:
        cost = self.cost_of(model, int(usage.get("prompt_tokens") or 0),
                            int(usage.get("completion_tokens") or 0))
        self.spent += cost
        self.calls += 1
        return cost


def call(key: str, model: str, system: str, user: str, max_tokens: int,
         retries: int = 3) -> dict:
    payload = json.dumps({
        "model": model,
        "messages": [{"role": "system", "content": system},
                     {"role": "user", "content": user}],
        "max_tokens": max_tokens,
        "temperature": 0.0,
    }).encode("utf-8")
    request = urllib.request.Request(
        ENDPOINT, data=payload,
        headers={"Authorization": f"Bearer {key}",
                 "Content-Type": "application/json"})
    last = ""
    for attempt in range(retries):
        try:
            with urllib.request.urlopen(request, timeout=120) as response:
                body = json.load(response)
            return {
                "text": body["choices"][0]["message"].get("content") or "",
                "usage": body.get("usage") or {},
                "finish": body["choices"][0].get("finish_reason", ""),
            }
        except urllib.error.HTTPError as error:
            last = f"HTTP {error.code}"
            if error.code in (429, 502, 503, 529):
                time.sleep(2 ** attempt)
                continue
            break
        except Exception as error:  # noqa: BLE001
            last = type(error).__name__
            time.sleep(2 ** attempt)
    return {"text": "", "usage": {}, "finish": f"error:{last}"}


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repeats", type=int, default=1,
                        help="how many times to run each fixture item")
    parser.add_argument("--ceiling", type=float, default=4.50)
    parser.add_argument("--seed", type=int, default=606)
    parser.add_argument("--out", type=Path,
                        default=ROOT / "data" / "grounded-labels.jsonl")
    args = parser.parse_args(argv[1:])

    key = openrouter_key(ROOT)
    if not key:
        print("no OpenRouter key found", file=sys.stderr)
        return 2

    pricing = openrouter_pricing(key, [CHEAP, FRONTIER, JUDGE])
    for model in (CHEAP, FRONTIER, JUDGE):
        if model not in pricing:
            print(f"model unavailable: {model}", file=sys.stderr)
            return 2
        rates = pricing[model]
        print(f"  {model:<32} in ${rates['prompt_per_mtok_usd']:.4f}/Mtok  "
              f"out ${rates['completion_per_mtok_usd']:.4f}/Mtok")

    budget = Budget(args.ceiling, pricing)
    rng = random.Random(args.seed)

    items = [i for i in ITEMS for _ in range(args.repeats)]
    rng.shuffle(items)
    counts: dict[str, int] = defaultdict(int)
    for item in items:
        counts[TIER_NAMES[item.tier]] += 1
    print("")
    print(f"{len(items)} prompts ({dict(counts)}), "
          f"ceiling ${args.ceiling:.2f}")
    print("")
    selected = items

    handle = args.out.open("w", encoding="utf-8")
    aborted = ""
    for index, row in enumerate(selected, 1):
        if any(budget.would_breach(m) for m in (CHEAP, FRONTIER, JUDGE)):
            aborted = f"ceiling reached after {index - 1} turns"
            break

        prompt = row.prompt()
        cheap = call(key, CHEAP, ANSWER_SYSTEM, prompt,
                     ANSWER_TOKENS.get(CHEAP, DEFAULT_ANSWER_TOKENS))
        budget.record(CHEAP, cheap["usage"])
        frontier = call(key, FRONTIER, ANSWER_SYSTEM, prompt,
                        ANSWER_TOKENS.get(FRONTIER, DEFAULT_ANSWER_TOKENS))
        budget.record(FRONTIER, frontier["usage"])

        # An empty answer is a RESULT, not a row to discard. A model that spends
        # its whole budget reasoning and returns nothing has failed the task, and
        # silently dropping those rows is how the model that fails most often
        # ends up looking best.
        if not cheap["text"] or not frontier["text"]:
            handle.write(json.dumps({
                "kind": row.kind, "tier": row.tier,
                "tier_name": TIER_NAMES[row.tier], "checked": "no_answer",
                "cheap_empty": not cheap["text"],
                "frontier_empty": not frontier["text"],
                "cheap_finish": cheap["finish"], "frontier_finish": frontier["finish"],
                "cheap_worse": bool(not cheap["text"] and frontier["text"]),
                "equivalent": bool(not cheap["text"] and not frontier["text"]),
                "cheap_tokens": cheap["usage"].get("completion_tokens"),
                "frontier_tokens": frontier["usage"].get("completion_tokens"),
                "cheap_prompt_tokens": cheap["usage"].get("prompt_tokens"),
                "frontier_prompt_tokens": frontier["usage"].get("prompt_tokens"),
            }, ensure_ascii=False) + chr(10))
            handle.flush()
            continue

        # A NO_MODEL item has a known answer, so it is checked exactly and never
        # sent to the judge. Nobody needs an opinion on whether 5496 is 5496,
        # and a judged verdict there would be strictly weaker evidence.
        if row.tier == 0 and row.expected:
            def _hit(text):
                cleaned = text.replace(",", "").replace("*", "").lower()
                return all(part.strip().replace(",", "").lower() in cleaned
                           for part in row.expected.split(","))
            cheap_ok, frontier_ok = _hit(cheap["text"]), _hit(frontier["text"])
            handle.write(json.dumps({
                "kind": row.kind, "tier": row.tier,
                "tier_name": TIER_NAMES[row.tier], "checked": "exact",
                "expected": row.expected,
                "cheap_correct": cheap_ok, "frontier_correct": frontier_ok,
                "cheap_worse": bool(frontier_ok and not cheap_ok),
                "equivalent": cheap_ok == frontier_ok,
                "cheap_tokens": cheap["usage"].get("completion_tokens"),
                "frontier_tokens": frontier["usage"].get("completion_tokens"),
                "cheap_prompt_tokens": cheap["usage"].get("prompt_tokens"),
                "frontier_prompt_tokens": frontier["usage"].get("prompt_tokens"),
            }, ensure_ascii=False) + chr(10))
            handle.flush()
            continue

        # Blind, order randomised, so the judge cannot infer which answer is
        # which from position alone.
        cheap_is_a = rng.random() < 0.5
        a, b = ((cheap, frontier) if cheap_is_a else (frontier, cheap))
        judge_prompt = (
            "REQUEST:" + chr(10) + row.request + chr(10) * 2
            + "SOURCE MATERIAL:" + chr(10) + row.payload + chr(10) * 2
            + "ANSWER A:" + chr(10) + a["text"] + chr(10) * 2
            + "ANSWER B:" + chr(10) + b["text"])
        verdict = call(key, JUDGE, JUDGE_SYSTEM, judge_prompt, MAX_JUDGE_TOKENS)
        budget.record(JUDGE, verdict["usage"])

        parsed = {"verdict": "UNPARSED", "reason": verdict["text"][:80]}
        try:
            start = verdict["text"].index("{")
            parsed = json.loads(verdict["text"][start:verdict["text"].rindex("}") + 1])
        except Exception:
            pass

        raw = str(parsed.get("verdict", "")).upper()
        if raw in ("A_WORSE", "B_WORSE"):
            cheap_worse = (raw == "A_WORSE") == cheap_is_a
        else:
            cheap_worse = False

        handle.write(json.dumps({
            "kind": row.kind, "tier": row.tier, "tier_name": TIER_NAMES[row.tier],
            "checked": "judge",
            "cheap_tokens": cheap["usage"].get("completion_tokens"),
            "frontier_tokens": frontier["usage"].get("completion_tokens"),
            "cheap_prompt_tokens": cheap["usage"].get("prompt_tokens"),
            "frontier_prompt_tokens": frontier["usage"].get("prompt_tokens"),
            "verdict": raw, "cheap_worse": cheap_worse,
            "equivalent": raw == "EQUIVALENT",
            "reason": str(parsed.get("reason", ""))[:120],
            "cheap_was_a": cheap_is_a,
        }, ensure_ascii=False) + "\n")
        handle.flush()

        if index % 25 == 0:
            print(f"  {index}/{len(selected)}  spent ${budget.spent:.3f}  "
                  f"({budget.calls} calls)")
    handle.close()

    print(f"\nspent ${budget.spent:.4f} of ${args.ceiling:.2f} "
          f"over {budget.calls} calls")
    if aborted:
        print(f"ABORTED: {aborted}")
    print(f"written: {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
